# A yaml version of params.py
sweep_name: null
seed: 0
gpu_id: '0'
lr: 0.0005
batch_size: 128
val_batch_size: 16
test_batch_size: 128
resolution: [64, 64] # Tuple[int, int]
num_slots: 7
latent_dim: 128
decoder_type: sbd
beta: 4
gamma: 0.0
data_mix_idx: 1
data_mix_csv: /checkpoint/siruixie/data_mix.csv
data_root:  /checkpoint/siruixie/clevr_corr/ #/datasets01/CLEVR_v1.0/060817/images/train/
val_root: /checkpoint/siruixie/clevr_with_masks/
test_root: /checkpoint/siruixie/clevr_obj_test/output/
gpus: 1
max_epochs: 100
num_sanity_val_steps: 1
scheduler_gamma: 0.95
weight_decay: 0.0
num_train_images: 23000 # Optional[int]
num_val_images: 10000  # Optional[int]
num_test_images: 1000
eval_every_n_epoch: 1
empty_cache: True
is_logger_enabled: True
is_verbose: True
num_workers: 10
n_samples: 5
warmup_steps: 10000
decay_steps: 100000
test_type: [obj, attr]
result_csv: /checkpoint/siruixie/data_mix_result.csv

hydra:
  sweep:
    dir: /checkpoint/${env:USER}/runs/objectness/${hydra.job.name}_${sweep_name}
    subdir: ${hydra.job.override_dirname}

  run:
    dir: outputs/${hydra.job.override_dirname}
