# A yaml version of params.py
sweep_name: null
seed: 0
gpu_id: '0, 1'
lr: 0.0004
batch_size: 64
val_batch_size: 16
test_batch_size: 256
resolution: [64, 64] # Tuple[int, int]
num_slots: 7
num_iterations: 4
data_root: /datasets01/CLEVR_v1.0/060817/images/
val_root: /checkpoint/siruixie/clevr_with_masks/
test_root: /checkpoint/siruixie/clevr_obj_test/output/
gpus: 2
max_epochs: 100
num_sanity_val_steps: 1
scheduler_gamma: 0.5
weight_decay: 0.0
num_train_images: null # Optional[int]
num_val_images: 10000  # Optional[int]
num_test_images: 1000
eval_every_n_epoch: 20
empty_cache: True
is_logger_enabled: True
is_verbose: True
num_workers: 10
n_samples: 5
warmup_steps_pct: 0.02
decay_steps_pct: 0.2
test_type: [obj, attr]
dup_threshold: 0.15

hydra:
  sweep:
    dir: /checkpoint/${env:USER}/runs/objectness/${hydra.job.name}_${sweep_name}
    subdir: ${hydra.job.override_dirname}

  run:
    dir: outputs/${hydra.job.override_dirname}
