# A yaml version of params.py
sweep_name: null
model: btc-vae
seed: 0
gpu_id: '0'
lr: 0.0002 # 3e-4 for iodine, 2e-4 for slot-attn
batch_size: 128 # 32 for slot-attn
val_batch_size: 16
test_batch_size: 64
resolution: [128, 128] # Tuple[int, int]
num_slots: 7
num_iterations: 4 # 5 for iodine, 4 for slot-attn
latent_dim: 256 # 256 for bvae
decoder_type: deconv # for bvae
alpha: 1. # for bvae
beta: 0. # for bvae
gamma: 1. # for bvae
sigma: 0.1 # for iodine
use_layernorm: True # for iodine
data_mix_idx: 0
data_mix_csv: /checkpoint/siruixie/data_mix.csv
data_root:  /checkpoint/siruixie/clevr_corr/ #/datasets01/CLEVR_v1.0/060817/images/train/
val_root: /checkpoint/siruixie/clevr_with_masks/
test_root: /checkpoint/siruixie/clevr_obj_test/output/obj_test_occ_prep/3/
gpus: 1
max_epochs: 300 # 1000 for iodine, 500 for slot-attn
num_sanity_val_steps: 1
scheduler_gamma: 1.0
weight_decay: 0.0
num_train_images: 23000 # Optional[int]
num_val_images: 10000  # Optional[int]
num_test_images: null
eval_every_n_epoch: 1
empty_cache: True
is_logger_enabled: True
is_verbose: True
num_workers: 10
n_samples: 4
anneal_steps: 10000
warmup_steps: 10000
decay_steps: 100000
test_type: obj
dup_threshold: 0.15
rm_invisible: True
result_csv: /checkpoint/siruixie/data_mix_result.csv
load_path: null

hydra:
  sweep:
    dir: /checkpoint/${env:USER}/runs/objectness/${hydra.job.name}_${sweep_name}
    subdir: ${hydra.job.override_dirname}

  run:
    dir: outputs/${hydra.job.override_dirname}
