#  yaml version of params.py
sweep_name: null
model: slot-attn
seed: 0
gpu_id: '0, 1'
lr: 0.0002 # 3e-4 for iodine, 2e-4 for slot-attn
batch_size: 32
val_batch_size: 2
test_batch_size: 4
test_mini_batch_size: 64
resolution: [128, 128] # Tuple[int, int]
num_slots: 7
num_iterations: 4
data_mix_idx: 1
data_mix_csv: /checkpoint/siruixie/data_mix.csv
data_root:  /checkpoint/siruixie/clevr_corr/ #/datasets01/CLEVR_v1.0/060817/images/train/
val_root: /checkpoint/siruixie/clevr_with_masks/
test_root: /checkpoint/siruixie/clevr_obj_test/output/
gpus: 2
max_epochs: 500 # 1000 for iodine, 500 for slot-attn
num_sanity_val_steps: 1
scheduler_gamma: 0.5
weight_decay: 0.0
num_train_images: 23000 # Optional[int]
num_val_images: 10000  # Optional[int]
num_test_images: null
eval_every_n_epoch: 1
empty_cache: True
is_logger_enabled: True
is_verbose: True
num_workers: 10
n_samples: 4
warmup_steps: 10000
decay_steps: 100000
test_type: obj
dup_threshold: 0.15
rm_invisible: True
num_checkpoints: 10
resume: False
result_csv: /checkpoint/siruixie/data_mix_result.csv

hydra:
        sweep:
                dir: /checkpoint/${env:USER}/runs/objectness/${hydra.job.name}_${sweep_name}
                subdir: ${hydra.job.override_dirname}

        run:
                dir: outputs/${hydra.job.override_dirname}
